
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'DBT_TRAINING_PROJECT'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'DBT_TRAINING_PROJECT'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  DBT_TRAINING_PROJECT:
    
    # Config indicated by + and applies to all files under models/example/
    customers_stg:
      schema: L2_PROCESSED_SCH
    products_stg:
      +materialized: table
    orders_stg:
      schema: L2_PROCESSED_SCH
    raws:
      schema: RAW
      vars:
        var_custs_id: 3
    transforms:
      schema: TRANSFORM
    consumptions:
      schema: CONSUMPTION
    +pre-hook:
      - "INSERT INTO DBT_DEMO.RAW.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME) VALUES ('{{ invocation_id }}','{{ this.name }}','STARTED',CURRENT_TIMESTAMP,NULL)"
    +post-hook:
      - "INSERT INTO DBT_DEMO.RAW.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME) VALUES ('{{ invocation_id }}','{{ this.name }}','COMPLETED',NULL,CURRENT_TIMESTAMP)"
on-run-start:
  - "INSERT INTO DBT_DEMO.RAW.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME) VALUES ('{{ invocation_id }}','ON-RUN-START','STARTED',CURRENT_TIMESTAMP,NULL)"
on-run-end:
  - "INSERT INTO DBT_DEMO.RAW.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME) VALUES ('{{ invocation_id }}','ON-RUN-END','COMPLETED',NULL,CURRENT_TIMESTAMP)"

seeds:
  DBT_TRAINING_PROJECT:
    # Config indicated by + and applies to all files under models/example/
    schema: RAW
    
snapshots:
  DBT_TRAINING_PROJECT:
    # Config indicated by + and applies to all files under models/example/
    schema: RAW

vars:
  var_cust_id: '1'