version: 2

snapshots:
  - name: products_snapshot
    description: Snapshot for Products Table with timestamp strategy
    columns:
      - name: product_id
        description: Product Id
      - name: product_name
        description: Name of the Product
      - name: unit_price
        description: Unit Price 
      - name: created_date
        description: Created Date
      - name: lastmodified_date
        description: Last Modified Date